CC := gcc
PKG_CONFIG := pkg-config

CPPFLAGS := -DBUILD_R36S
CFLAGS := -O2 -Wall -Wextra
PKG_CFLAGS := $(shell $(PKG_CONFIG) --cflags sdl2 SDL2_mixer SDL2_ttf libcurl libsystemd libqrencode)
PKG_LIBS := $(shell $(PKG_CONFIG) --libs sdl2 SDL2_mixer SDL2_ttf libcurl libsystemd libqrencode)
LDFLAGS := -Wl,-rpath,'$$ORIGIN/lib' -Wl,--wrap=load_playback_config -Wl,--wrap=save_playback_config \
	-Wl,--wrap=remote_download_selection -Wl,--wrap=input_normalize_event \
	-Wl,--wrap=downloadbrowser_handle_event -Wl,--wrap=downloadbrowser_render \
	-Wl,--wrap=player_render -Wl,--wrap=SDL_Quit

SOURCES := \
	main.c \
	util.c \
	config_update.c \
	download_config_save.c \
	playback_runtime.c \
	hardware_config_save.c \
	stream_config.c \
	stream_favorites.c \
	update_config.c \
	state.c \
	backlight.c \
	battery.c \
	battery_bluez.c \
	led.c \
	scanner.c \
	audio.c \
	output_volume.c \
	ui.c \
	storage.c \
	local_delete.c \
	systemstats.c \
	media_keys.c \
	media_feedback.c \
	app_log.c \
	input_config.c \
	streaming.c \
	qr_render.c \
	mpris_bridge.c \
	bluetooth.c \
	bluetooth_audio_sink.c \
	bluez_discovery.c \
	batocera_pair_agent.c \
	hfp_gateway.c \
	pbap_phonebook.c \
	download.c \
	background_download.c \
	background_download_ui.c \
	screens/menu.c \
	screens/tracks.c \
	screens/player.c \
	screens/systemmenu.c \
	screens/systeminfo.c \
	screens/buttondebug.c \
	screens/downloadbrowser.c \
	screens/streams.c \
	screens/streamsettings.c \
	screens/updatesettings.c \
	screens/logview.c \
	screens/bluetooth.c \
	screens/downloadsettings.c

OBJECTS := $(SOURCES:.c=.o)

.PHONY: all clean

all: hoerspiel_player

hoerspiel_player: $(OBJECTS)
	$(CC) $(LDFLAGS) -o $@ $(OBJECTS) $(PKG_LIBS)

led.o: led.c hardware_config_save.h
	$(CC) $(CPPFLAGS) $(CFLAGS) $(PKG_CFLAGS) -include hardware_config_save.h -Dset_led_gpio_config=hardware_config_save_led_gpio -c $< -o $@

streaming.o: streaming.c network_limits.h
	$(CC) $(CPPFLAGS) $(CFLAGS) $(PKG_CFLAGS) -include network_limits.h -c $< -o $@
download.o: download.c network_limits.h
	$(CC) $(CPPFLAGS) $(CFLAGS) $(PKG_CFLAGS) -include network_limits.h -c $< -o $@

%.o: %.c
	$(CC) $(CPPFLAGS) $(CFLAGS) $(PKG_CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJECTS) hoerspiel_player
