CC := gcc
PKG_CONFIG := pkg-config

CPPFLAGS := -DBUILD_BATOCERA
CFLAGS := -O2 -Wall -Wextra
LDFLAGS := -Wl,--wrap=system -Wl,--wrap=load_playback_config -Wl,--wrap=save_playback_config \
	-Wl,--wrap=remote_download_selection -Wl,--wrap=input_normalize_event \
	-Wl,--wrap=downloadbrowser_handle_event -Wl,--wrap=downloadbrowser_render \
	-Wl,--wrap=player_handle_event -Wl,--wrap=player_render -Wl,--wrap=SDL_Quit \
	-Wl,--wrap=bluetooth_scan_paired_trusted -Wl,--wrap=bluetooth_connect_device \
	-Wl,--wrap=bluetooth_autoconnect_start -Wl,--wrap=batocera_set_bluetooth_enabled \
	-Wl,--wrap=bluetoothscreen_reset -Wl,--wrap=bluetoothscreen_handle_event \
	-Wl,--wrap=bluetoothscreen_render
PKG_CFLAGS := $(shell $(PKG_CONFIG) --cflags sdl2 SDL2_mixer SDL2_ttf libcurl libsystemd libqrencode)
PKG_LIBS := $(shell $(PKG_CONFIG) --libs sdl2 SDL2_mixer SDL2_ttf libcurl libsystemd libqrencode)

SOURCES := \
	main.c \
	app_shutdown.c \
	util.c \
	config_update.c \
	download_config_save.c \
	playback_runtime.c \
	hardware_config_save.c \
	stream_config.c \
	stream_favorites.c \
	update_config.c \
	state.c \
	backlight.c \
	battery.c \
	battery_bluez.c \
	led.c \
	scanner.c \
	audio.c \
	output_volume.c \
	ui.c \
	storage.c \
	local_delete.c \
	systemstats.c \
	media_keys.c \
	media_feedback.c \
	app_log.c \
	input_config.c \
	gpm2804_player_volume.c \
	streaming.c \
	qr_render.c \
	mpris_bridge.c \
	bluetooth.c \
	bluetooth_audio_sink.c \
	bluez_discovery.c \
	batocera_bluetooth.c \
	batocera_pair_agent.c \
	batocera_bluetooth_override.c \
	batocera_bluetooth_ui.c \
	hfp_gateway.c \
	pbap_phonebook.c \
	download.c \
	background_download.c \
	background_download_ui.c \
	screens/menu.c \
	screens/tracks.c \
	screens/player.c \
	screens/systemmenu.c \
	screens/systeminfo.c \
	screens/buttondebug.c \
	screens/downloadbrowser.c \
	screens/streams.c \
	screens/streamsettings.c \
	screens/updatesettings.c \
	screens/logview.c \
	screens/bluetooth.c \
	screens/downloadsettings.c

OBJECTS := $(SOURCES:.c=.o)

.PHONY: all clean test-utils

all: hoerspiel_player

hoerspiel_player: $(OBJECTS)
	$(CC) $(LDFLAGS) -o $@ $(OBJECTS) $(PKG_LIBS)

test-utils:
	$(CC) $(CFLAGS) -I. tests/test_util_config.c util.c config_update.c -o /tmp/hoerspiel-test-util-config
	/tmp/hoerspiel-test-util-config
	rm -f /tmp/hoerspiel-test-util-config

led.o: led.c hardware_config_save.h
	$(CC) $(CPPFLAGS) $(CFLAGS) $(PKG_CFLAGS) -include hardware_config_save.h -Dset_led_gpio_config=hardware_config_save_led_gpio -c $< -o $@

streaming.o: streaming.c network_limits.h
	$(CC) $(CPPFLAGS) $(CFLAGS) $(PKG_CFLAGS) -include network_limits.h -c $< -o $@
download.o: download.c network_limits.h
	$(CC) $(CPPFLAGS) $(CFLAGS) $(PKG_CFLAGS) -include network_limits.h -c $< -o $@

%.o: %.c
	$(CC) $(CPPFLAGS) $(CFLAGS) $(PKG_CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJECTS) hoerspiel_player
