#ifndef SCREENS_H
#define SCREENS_H

typedef enum {
    SCREEN_MENU = 0,
    SCREEN_TRACKS = 1,
    SCREEN_PLAYER = 2,
    SCREEN_SLEEP_TIMER = 3,
    SCREEN_SYSTEM_INFO = 4,
    SCREEN_BUTTON_DEBUG = 5,
    SCREEN_SYSTEM_MENU = 6,
    SCREEN_DOWNLOADS = 7,
    SCREEN_LOG = 8,
    SCREEN_BLUETOOTH = 9,
    SCREEN_DOWNLOAD_SETTINGS = 10,
    SCREEN_STREAMS = 11
} ScreenId;

#endif
