#include "streams.h"
#include "../streaming.h"
#include "../stream_favorites.h"
#include "../ui.h"
#include "../state.h"
#include "../systemstats.h"
#include <stdio.h>
#include <stdlib.h>
#include <SDL2/SDL_mixer.h>

static StreamEntry *entries=NULL;
static int count=0,selection=0,loaded=0,loading=0,favorites_only=0;
static int return_filter_valid=0,return_favorites_only=0;
static char status[256]="",last_selected_uuid[STREAM_UUID_LEN]="";
static int total_favorites(void){int n=0;for(int i=0;i<count;i++)if(stream_favorite_is_set(entries[i].uuid))n++;return n;}
static int visible_count(void){if(!favorites_only)return count;int n=0;for(int i=0;i<count;i++)if(stream_favorite_is_set(entries[i].uuid))n++;return n;}
static int actual_index(int vi){if(!favorites_only)return vi;int n=0;for(int i=0;i<count;i++)if(stream_favorite_is_set(entries[i].uuid)){if(n==vi)return i;n++;}return -1;}
static void clamp_selection(void);
static int visible_index_for_uuid(const char *uuid){if(!uuid||!uuid[0])return -1;if(!favorites_only){for(int i=0;i<count;i++)if(!strcmp(entries[i].uuid,uuid))return i;return -1;}int vi=0;for(int i=0;i<count;i++){if(!stream_favorite_is_set(entries[i].uuid))continue;if(!strcmp(entries[i].uuid,uuid))return vi;vi++;}return -1;}
static void remember_current_selection(void){int n=visible_count();if(n<=0)return;int ai=actual_index(selection);if(ai<0||ai>=count)return;if(entries[ai].uuid[0])snprintf(last_selected_uuid,sizeof(last_selected_uuid),"%s",entries[ai].uuid);}
static void restore_selection_from_uuid(void){int vi=visible_index_for_uuid(last_selected_uuid);if(vi>=0)selection=vi;else clamp_selection();}
static void clamp_selection(void){int n=visible_count();if(n<=0)selection=0;else if(selection>=n)selection=n-1;if(selection<0)selection=0;}
void streams_reset(void){free(entries);entries=NULL;count=0;selection=0;loaded=0;loading=0;favorites_only=0;status[0]='\0';}
static void load_streams(void){loading=1;if(!stream_xml_url[0]){free(entries);entries=NULL;count=0;selection=0;snprintf(status,sizeof(status),"Stream-XML nicht konfiguriert");loaded=1;loading=0;return;}if(!network_connection_active()){free(entries);entries=NULL;count=0;selection=0;snprintf(status,sizeof(status),"Keine Netzwerkverbindung");loaded=1;loading=0;return;}free(entries);entries=NULL;count=0;if(streaming_fetch_xml(&entries,&count,status,sizeof(status))!=0){free(entries);entries=NULL;count=0;}if(return_filter_valid){favorites_only=return_favorites_only;return_filter_valid=0;if(favorites_only&&total_favorites()==0)favorites_only=0;}else favorites_only=total_favorites()>0;selection=0;if(last_selected_uuid[0])restore_selection_from_uuid();else clamp_selection();loaded=1;loading=0;}
void streams_handle_event(ScreenContext *c,const SDL_Event *e){if(!loaded&&!loading)load_streams();if(e->type!=SDL_JOYBUTTONDOWN)return;int b=e->jbutton.button,n=visible_count();if(b==BUTTON_B||b==BUTTON_DPAD_LEFT){*c->screen=SCREEN_SYSTEM_MENU;return;}if(b==BUTTON_X){remember_current_selection();favorites_only=!favorites_only;selection=0;restore_selection_from_uuid();status[0]='\0';return;}if(b==BUTTON_Y&&n>0){int ai=actual_index(selection);if(ai>=0&&entries[ai].uuid[0]){int r=stream_favorite_toggle(entries[ai].uuid);snprintf(status,sizeof(status),r>0?"Favorit gesetzt":"Favorit entfernt");clamp_selection();}else snprintf(status,sizeof(status),"Keine stationuuid vorhanden");return;}if(b==BUTTON_DPAD_UP&&n){if(--selection<0)selection=n-1;return;}if(b==BUTTON_DPAD_DOWN&&n){if(++selection>=n)selection=0;return;}if(b==BUTTON_L1&&n){int page=(SCREEN_H-145)/menu_line_height();if(page<1)page=1;selection-=page;if(selection<0)selection=0;return;}if(b==BUTTON_R1&&n){int page=(SCREEN_H-145)/menu_line_height();if(page<1)page=1;selection+=page;if(selection>=n)selection=n-1;return;}if(b==BUTTON_L2&&n){selection=0;return;}if(b==BUTTON_R2&&n){selection=n-1;return;}if((b==BUTTON_A||b==BUTTON_DPAD_RIGHT)&&n){int ai=actual_index(selection);if(ai<0)return;if(entries[ai].uuid[0])snprintf(last_selected_uuid,sizeof(last_selected_uuid),"%s",entries[ai].uuid);return_favorites_only=favorites_only;return_filter_valid=1;char err[256]="";if(streaming_start(&entries[ai],err,sizeof(err))==0){if(c->music&&*c->music&&Mix_PlayingMusic()&&!Mix_PausedMusic())Mix_PauseMusic();streaming_set_volume((volume*100)/128);*c->screen=SCREEN_PLAYER;}else snprintf(status,sizeof(status),"%s",err);}}
void streams_render(ScreenContext *c){if(!loaded&&!loading)load_streams();menu_font_apply(c->font);char heading[192];snprintf(heading,sizeof(heading),"Streams - %s  [%s]",favorites_only?"Favoriten":"Alle",streaming_backend_name());draw_text(c->renderer,c->font,heading,20,20,c->selected);if(!streaming_backend_available())draw_text(c->renderer,c->font,"Kein Streaming-Backend verfuegbar",20,48,c->gray);int n=visible_count();if(!n){draw_text(c->renderer,c->font,favorites_only?"Keine Favoriten":"Keine Streams",20,80,c->gray);if(status[0])draw_text(c->renderer,c->font,status,20,115,c->gray);draw_text(c->renderer,c->font,"X: Alle/Favoriten   Y: Favorit",20,SCREEN_H-55,c->gray);draw_text(c->renderer,c->font,"B/Links: Zurueck",20,SCREEN_H-30,c->gray);menu_font_restore(c->font);return;}int row=menu_line_height(),top=65,visible=(SCREEN_H-145)/row;if(visible<1)visible=1;int start=selection>=visible?selection-visible+1:0,y=top;for(int vi=start;vi<n&&vi<start+visible;vi++,y+=row){int ai=actual_index(vi);if(ai<0)continue;char label[STREAM_NAME_LEN+8];snprintf(label,sizeof(label),"%s%s",stream_favorite_is_set(entries[ai].uuid)?"* ":"",entries[ai].name);draw_text(c->renderer,c->font,label,35,y,vi==selection?c->selected:c->white);}draw_scrollbar(c->renderer,620,top,visible*row,n,visible,start);char info[256];snprintf(info,sizeof(info),"%d/%d  Y: Favorit  X: %s",selection+1,n,favorites_only?"Alle":"Favoriten");if(status[0])draw_text(c->renderer,c->font,status,20,SCREEN_H-82,c->gray);draw_text(c->renderer,c->font,info,20,SCREEN_H-55,c->gray);draw_text(c->renderer,c->font,"A/Rechts: Start  L1/R1: Seite  L2/R2: Anfang/Ende",20,SCREEN_H-30,c->gray);menu_font_restore(c->font);}
