#include "systeminfo.h"
#include "../backlight.h"
#include "../state.h"
#include "../ui.h"
#include "../led.h"
#include "../storage.h"
#include "../bluetooth.h"
#include "../output_volume.h"
#include "../systemstats.h"
#include "../battery.h"
#include "../streaming.h"
#include "streamsettings.h"
#include "updatesettings.h"
#include "bluetooth.h"
#include "downloadsettings.h"
#include "buttondebug.h"
#include "logview.h"
#include <stdio.h>
#include <string.h>
#include <sys/statvfs.h>
#include <sys/utsname.h>
#include <stdlib.h>
#include <unistd.h>
#include <pwd.h>

static int page_offset=0,selected_line=1,sleep_timer_edit_minutes=-1;
static const int BRIGHTNESS_STEP=5;
#define LINE_H (menu_line_height())
static const int TOP_Y=58;
#define MAX_VISIBLE ((SCREEN_H-95-TOP_Y)/LINE_H)
static const int DISPLAY_TIMEOUTS[]={0,15,30,60,120,300,600};
#define DISPLAY_TIMEOUT_COUNT ((int)(sizeof(DISPLAY_TIMEOUTS)/sizeof(DISPLAY_TIMEOUTS[0])))
typedef struct{char label[64];char value[384];int heading;}InfoLine;
static void add_line(InfoLine*l,int*n,const char*a,const char*v,int h){if(*n>=64)return;snprintf(l[*n].label,sizeof(l[*n].label),"%s",a?a:"");snprintf(l[*n].value,sizeof(l[*n].value),"%s",v?v:"");l[*n].heading=h;(*n)++;}
static void format_uptime(char*out,size_t z){FILE*f=fopen("/proc/uptime","r");double s=0;if(f){fscanf(f,"%lf",&s);fclose(f);}long q=(long)s;int d=q/86400;q%=86400;int h=q/3600;q%=3600;int m=q/60;q%=60;if(d)snprintf(out,z,"%dd %02d:%02d:%02ld",d,h,m,q);else snprintf(out,z,"%02d:%02d:%02ld",h,m,q);}
static void format_memory(char*out,size_t z){FILE*f=fopen("/proc/meminfo","r");unsigned long long t=0,a=0,v;char k[64],u[16];if(f){while(fscanf(f,"%63s %llu %15s",k,&v,u)==3){if(!strcmp(k,"MemTotal:"))t=v;else if(!strcmp(k,"MemAvailable:"))a=v;}fclose(f);}if(!t){snprintf(out,z,"--");return;}snprintf(out,z,"%llu / %llu MB",(t-a)/1024,t/1024);}
static void format_free_space(const char*p,char*out,size_t z){struct statvfs v;if(statvfs(p,&v)!=0){snprintf(out,z,"nicht verfuegbar");return;}unsigned long long t=(unsigned long long)v.f_blocks*v.f_frsize,f=(unsigned long long)v.f_bavail*v.f_frsize;if(t>=1073741824ULL)snprintf(out,z,"%.1f GB frei / %.1f GB",f/1073741824.0,t/1073741824.0);else snprintf(out,z,"%.0f MB frei / %.0f MB",f/1048576.0,t/1048576.0);}
static void format_alsa_device(char*out,size_t z){FILE*f=fopen("/proc/asound/cards","r");char line[256],name[128]="";int card=-1;if(f){while(fgets(line,sizeof(line),f)){int n;if(sscanf(line," %d [%127[^]]",&n,name)==2){card=n;break;}}fclose(f);}if(card>=0){snprintf(out,z,name[0]?"hw:%d,0  %s":"hw:%d,0",card,name);return;}snprintf(out,z,"--");}
static void format_audio_output(char*out,size_t z){const char*d=SDL_GetCurrentAudioDriver();int n=SDL_GetNumAudioDevices(0);const char*x=n>0?SDL_GetAudioDeviceName(0,0):NULL;if(x&&*x&&d&&*d)snprintf(out,z,"%s (%s)",x,d);else if(x&&*x)snprintf(out,z,"%s",x);else if(d&&*d)snprintf(out,z,"%s",d);else snprintf(out,z,"--");}
static void format_display_timeout(char*out,size_t z){if(display_timeout_seconds<=0)snprintf(out,z,"<  Aus  >");else if(display_timeout_seconds<60)snprintf(out,z,"<  %d s  >",display_timeout_seconds);else if(display_timeout_seconds%60==0)snprintf(out,z,"<  %d min  >",display_timeout_seconds/60);else snprintf(out,z,"<  %d s  >",display_timeout_seconds);}
static void format_usage_time(unsigned long long s,char*out,size_t z){unsigned long long d=s/86400;s%=86400;unsigned long long h=s/3600;s%=3600;unsigned long long m=s/60;if(d)snprintf(out,z,"%llu d %02llu:%02llu",d,h,m);else snprintf(out,z,"%02llu:%02llu h",h,m);}
static void format_battery_time(int ch,char*out,size_t z){int m=ch?get_battery_charge_remaining_minutes():get_battery_remaining_minutes();if(m<0){snprintf(out,z,"--");return;}if(ch&&m==0){snprintf(out,z,"voll");return;}if(m>=60)snprintf(out,z,"ca. %d h %02d min",m/60,m%60);else snprintf(out,z,"ca. %d min",m);}
static int build_lines(ScreenContext*c,InfoLine*l){int n=0;char b[512];add_line(l,&n,"TIMER","",1);int sm=sleep_timer_edit_minutes>=0?sleep_timer_edit_minutes:*c->sleep_timer_minutes;if(sleep_timer_edit_minutes>=0)snprintf(b,sizeof(b),sm>0?"<  %d min  >  A: OK":"<  Aus  >  A: OK",sm);else if(*c->sleep_timer_active){Uint32 now=SDL_GetTicks(),r=*c->sleep_timer_end_ticks>now?*c->sleep_timer_end_ticks-now:0;snprintf(b,sizeof(b),"<  %d min  >  %d:%02d",*c->sleep_timer_minutes,(int)(r/60000),(int)((r/1000)%60));}else if(*c->sleep_timer_minutes>0)snprintf(b,sizeof(b),"<  %d min  >",*c->sleep_timer_minutes);else snprintf(b,sizeof(b),"<  Aus  >");add_line(l,&n,"Sleeptimer",b,0);snprintf(b,sizeof(b),idle_timer_minutes>0?"<  %d min  >":"<  Aus  >",idle_timer_minutes);add_line(l,&n,"Idle-Timer",b,0);snprintf(b,sizeof(b),shutdown_after_tracks>0?"<  %d Tracks  >":"<  Aus  >",shutdown_after_tracks);add_line(l,&n,"Shutdown nach Tracks",b,0);snprintf(b,sizeof(b),"<  %s  >",shutdown_at_book_end?"An":"Aus");add_line(l,&n,"Shutdown am Ende",b,0);
add_line(l,&n,"DOWNLOADS / STREAMS","",1);int net=network_connection_active();snprintf(b,sizeof(b),net?"<  Oeffnen  >":"nicht verfuegbar");add_line(l,&n,"Downloads",b,0);snprintf(b,sizeof(b),(net&&stream_xml_url[0])?"<  Oeffnen  >":(stream_xml_url[0]?"nicht verfuegbar":"XML nicht gesetzt"));add_line(l,&n,"Streams",b,0);
add_line(l,&n,"AUDIO / DISPLAY","",1);
#ifdef BUILD_BATOCERA
snprintf(b,sizeof(b),"<  %s  >",bluetooth_adapter_powered()?"An":"Aus");add_line(l,&n,"Bluetooth System",b,0);
#endif
snprintf(b,sizeof(b),bluetooth_adapter_powered()?"<  Oeffnen  >":(bluetooth_adapter_present()?"ausgeschaltet":"nicht verfuegbar"));add_line(l,&n,"Bluetooth",b,0);
int ov=-1;if(output_volume_get(&ov)==0)snprintf(b,sizeof(b),"<  %d %%  >",ov);else snprintf(b,sizeof(b),"nicht verfuegbar");add_line(l,&n,"Ausgangslautstaerke",b,0);
snprintf(b,sizeof(b),"<  %d %%  >",(volume*100)/MIX_MAX_VOLUME);add_line(l,&n,"Lautstaerke",b,0);
char sink[512];int bv=-1;if(bluetooth_audio_sink_get(sink,sizeof(sink),&bv)==0&&sink[0]&&bv>=0){snprintf(b,sizeof(b),"<  %d %%  >",bv);add_line(l,&n,"Bluetooth-Lautstaerke",b,0);}
int br=get_brightness_percent();if(br>=0)snprintf(b,sizeof(b),"<  %d %%  >",br);else strcpy(b,"--");add_line(l,&n,"Helligkeit",b,0);format_display_timeout(b,sizeof(b));add_line(l,&n,"Display aus nach",b,0);static const char*fn[]={"Klein","Normal","Gross","Sehr gross"};snprintf(b,sizeof(b),"<  %s  >",fn[menu_font_size]);add_line(l,&n,"Schriftgroesse",b,0);snprintf(b,sizeof(b),"<  %s  >",ui_accent_name());add_line(l,&n,"Akzentfarbe",b,0);
#ifdef BUILD_R36S
int g=led_get_gpio();if(g>=0)snprintf(b,sizeof(b),"<  %d  >  %s%s",g,led_gpio_is_manual()?"Manuell":"Auto",led_gpio_available(g)?"":" / nicht verfuegbar");else snprintf(b,sizeof(b),"<  Auto  >  nicht erkannt");add_line(l,&n,"LED GPIO",b,0);snprintf(b,sizeof(b),"<  %s  >",led_test_mode()?"An":"Aus");add_line(l,&n,"LED Test",b,0);
#endif
add_line(l,&n,"WIEDERGABE","",1);snprintf(b,sizeof(b),"<  %s  >",repeat_book?"Wiederholen":"Stop am Ende");add_line(l,&n,"Hoerspielende",b,0);add_line(l,&n,"NUTZUNGSSTATISTIK","",1);snprintf(b,sizeof(b),"%llu",usage_app_starts);add_line(l,&n,"App-Starts",b,0);format_usage_time(usage_runtime_seconds,b,sizeof(b));add_line(l,&n,"Laufzeit gesamt",b,0);format_usage_time(usage_playback_seconds,b,sizeof(b));add_line(l,&n,"Hoerzeit gesamt",b,0);
#ifdef BUILD_BATOCERA
add_line(l,&n,"FUNK","",1);snprintf(b,sizeof(b),"<  %s  >",batocera_wifi_enabled()?"An":"Aus");add_line(l,&n,"WLAN",b,0);
#endif
add_line(l,&n,"SYSTEM","",1);add_line(l,&n,"Updates","<  Oeffnen  >",0);snprintf(b,sizeof(b),"%s",APP_VERSION);add_line(l,&n,"Version",b,0);add_line(l,&n,"Config",get_storage_config_path(),0);struct passwd*pw=getpwuid(geteuid());if(pw&&pw->pw_name&&pw->pw_name[0])snprintf(b,sizeof(b),"%s (UID %lu)",pw->pw_name,(unsigned long)geteuid());else snprintf(b,sizeof(b),"UID %lu",(unsigned long)geteuid());add_line(l,&n,"Benutzer",b,0);if(network_get_active_ipv4(b,sizeof(b)))add_line(l,&n,"IP-Adresse",b,0);else add_line(l,&n,"IP-Adresse","nicht verbunden",0);struct utsname u;if(uname(&u)==0){add_line(l,&n,"Kernel",u.release,0);add_line(l,&n,"Architektur",u.machine,0);add_line(l,&n,"Hostname",u.nodename,0);}format_uptime(b,sizeof(b));add_line(l,&n,"Uptime",b,0);
add_line(l,&n,"LEISTUNG","",1);if(*c->cpu_usage>=0)snprintf(b,sizeof(b),"%.0f %%",*c->cpu_usage);else strcpy(b,"--");add_line(l,&n,"CPU",b,0);if(*c->cpu_temperature>=0)snprintf(b,sizeof(b),"%.1f °C",*c->cpu_temperature);else strcpy(b,"--");add_line(l,&n,"CPU-Temperatur",b,0);format_memory(b,sizeof(b));add_line(l,&n,"RAM",b,0);if(*c->ram_usage>=0)snprintf(b,sizeof(b),"%.0f %%",*c->ram_usage);else strcpy(b,"--");add_line(l,&n,"RAM-Auslastung",b,0);
add_line(l,&n,"AKKU / AUDIO","",1);if(*c->battery_percent>=0)snprintf(b,sizeof(b),"%d %%",*c->battery_percent);else strcpy(b,"--");add_line(l,&n,"Akku",b,0);add_line(l,&n,"Ladezustand",*c->battery_charging==1?"Laedt":"Entlaedt",0);format_battery_time(*c->battery_charging==1,b,sizeof(b));add_line(l,&n,*c->battery_charging==1?"Bis voll":"Restlaufzeit",b,0);format_audio_output(b,sizeof(b));add_line(l,&n,"Audio-Ausgabe",b,0);format_alsa_device(b,sizeof(b));add_line(l,&n,"ALSA-Device",b,0);add_line(l,&n,"Display",is_display_off()?"Aus":"An",0);add_line(l,&n,"SPEICHER","",1);for(int i=0;i<*c->storage_path_count;i++){if(c->storage_paths[i].available)format_free_space(c->storage_paths[i].path,b,sizeof(b));else snprintf(b,sizeof(b),"nicht verfuegbar");add_line(l,&n,c->storage_paths[i].path,b,0);}add_line(l,&n,"PROJEKT / KONTAKT","",1);add_line(l,&n,"GitHub","github.com/Gunnar82/book_player_r36s",0);add_line(l,&n,"Kontakt","gunnar_82@hotmail.com",0);add_line(l,&n,"DIAGNOSE","",1);add_line(l,&n,"Button Debug","<  Oeffnen  >",0);add_line(l,&n,"Programm-Log","<  Oeffnen  >",0);return n;}
static int find_line(InfoLine*l,int n,const char*s){for(int i=0;i<n;i++)if(!strcmp(l[i].label,s))return i;return-1;}static int line_selectable(const InfoLine*l){if(l->heading)return 0;
#ifdef BUILD_BATOCERA
if(!strcmp(l->label,"Bluetooth")&&!bluetooth_adapter_powered())return 0;
#endif
return 1;}static int next_selectable(InfoLine*l,int n,int f,int d){int i=f+d;while(i>=0&&i<n){if(line_selectable(&l[i]))return i;i+=d;}return f;}static void keep_visible(int n){int m=n-MAX_VISIBLE;if(m<0)m=0;if(selected_line<page_offset)page_offset=selected_line;if(selected_line>=page_offset+MAX_VISIBLE)page_offset=selected_line-MAX_VISIBLE+1;if(page_offset<0)page_offset=0;if(page_offset>m)page_offset=m;}
static void persist_playback_config(void){if(save_playback_config()!=0)fprintf(stderr,"Einstellungen: config.ini konnte nicht gespeichert werden.\n");}static void toggle_repeat_book(void){repeat_book=!repeat_book;persist_playback_config();}static void change_shutdown_tracks(int d){shutdown_after_tracks+=d;if(shutdown_after_tracks<0)shutdown_after_tracks=0;if(shutdown_after_tracks>999)shutdown_after_tracks=999;persist_playback_config();}static void toggle_shutdown_end(void){shutdown_at_book_end=!shutdown_at_book_end;persist_playback_config();}static void change_volume(int d){volume+=d;if(volume<0)volume=0;if(volume>MIX_MAX_VOLUME)volume=MIX_MAX_VOLUME;Mix_VolumeMusic(volume);save_state();}static void change_output(int d){output_volume_change(d,NULL);}static void change_bt(int d){char s[512];int v;if(bluetooth_audio_sink_get(s,sizeof(s),&v)!=0||!s[0])return;v+=d;if(v<0)v=0;if(v>100)v=100;bluetooth_audio_sink_set_volume(s,v);}static void change_brightness(int d){int p=get_brightness_percent();if(p<0)return;p+=d;if(p<10)p=10;if(p>100)p=100;set_brightness_percent(p);}static void change_display_timeout(int d){int x=0;for(int i=0;i<DISPLAY_TIMEOUT_COUNT;i++)if(DISPLAY_TIMEOUTS[i]==display_timeout_seconds)x=i;x+=d;if(x<0)x=DISPLAY_TIMEOUT_COUNT-1;if(x>=DISPLAY_TIMEOUT_COUNT)x=0;display_timeout_seconds=DISPLAY_TIMEOUTS[x];save_state();}static void edit_sleep_timer(ScreenContext*c,int d){if(sleep_timer_edit_minutes<0)sleep_timer_edit_minutes=*c->sleep_timer_minutes;sleep_timer_edit_minutes+=d;if(sleep_timer_edit_minutes<SLEEP_MIN_MINUTES)sleep_timer_edit_minutes=SLEEP_MIN_MINUTES;if(sleep_timer_edit_minutes>SLEEP_MAX_MINUTES)sleep_timer_edit_minutes=SLEEP_MAX_MINUTES;}static void confirm_sleep_timer(ScreenContext*c){int m=sleep_timer_edit_minutes>=0?sleep_timer_edit_minutes:*c->sleep_timer_minutes;*c->sleep_timer_minutes=m;if(m==0){*c->sleep_timer_active=0;*c->sleep_timer_end_ticks=0;}else{*c->sleep_timer_active=1;*c->sleep_timer_end_ticks=SDL_GetTicks()+(Uint32)(m*60000);}sleep_timer_edit_minutes=-1;}static void change_idle_timer(int d){idle_timer_minutes+=d;if(idle_timer_minutes<0)idle_timer_minutes=0;if(idle_timer_minutes>IDLE_TIMER_MAX_MINUTES)idle_timer_minutes=IDLE_TIMER_MAX_MINUTES;save_state();}
#ifdef BUILD_R36S
static void change_led_gpio(int d){int g=led_get_gpio();if(g<0)g=0;else g+=d;if(g<0)g=0;if(g>511)g=511;led_set_gpio_manual(g);}
#endif
void systeminfo_handle_event(ScreenContext*c,const SDL_Event*e){InfoLine l[64];int n=build_lines(c,l);if(selected_line>=n)selected_line=n-1;if(selected_line<0)selected_line=0;if(n>0&&!line_selectable(&l[selected_line]))selected_line=next_selectable(l,n,selected_line,1);if(e->type==SDL_JOYBUTTONDOWN){int b=e->jbutton.button;if(b==BUTTON_B){
#ifdef BUILD_R36S
led_set_test_mode(0);
#endif
sleep_timer_edit_minutes=-1;page_offset=0;selected_line=1;*c->screen=SCREEN_SYSTEM_MENU;return;}if(b==BUTTON_L1){for(int i=0;i<MAX_VISIBLE;i++)selected_line=next_selectable(l,n,selected_line,-1);keep_visible(n);return;}if(b==BUTTON_L2){selected_line=0;while(selected_line<n&&!line_selectable(&l[selected_line]))selected_line++;page_offset=0;return;}if(b==BUTTON_R1){for(int i=0;i<MAX_VISIBLE;i++)selected_line=next_selectable(l,n,selected_line,1);keep_visible(n);return;}if(b==BUTTON_R2){selected_line=n-1;while(selected_line>0&&!line_selectable(&l[selected_line]))selected_line--;keep_visible(n);return;}if(b==BUTTON_DPAD_UP){selected_line=next_selectable(l,n,selected_line,-1);keep_visible(n);return;}if(b==BUTTON_DPAD_DOWN){selected_line=next_selectable(l,n,selected_line,1);keep_visible(n);return;}int vl=find_line(l,n,"Lautstaerke"),ov=find_line(l,n,"Ausgangslautstaerke"),bv=find_line(l,n,"Bluetooth-Lautstaerke"),bl=find_line(l,n,"Helligkeit"),dt=find_line(l,n,"Display aus nach"),fl=find_line(l,n,"Schriftgroesse"),ac=find_line(l,n,"Akzentfarbe"),sl=find_line(l,n,"Sleeptimer"),il=find_line(l,n,"Idle-Timer"),rl=find_line(l,n,"Hoerspielende"),st=find_line(l,n,"Shutdown nach Tracks"),se=find_line(l,n,"Shutdown am Ende"),dl=find_line(l,n,"Downloads"),oz=find_line(l,n,"Streams"),up=find_line(l,n,"Updates"),bt=find_line(l,n,"Bluetooth"),bd=find_line(l,n,"Button Debug"),pl=find_line(l,n,"Programm-Log");
#ifdef BUILD_R36S
int gl=find_line(l,n,"LED GPIO"),tl=find_line(l,n,"LED Test");
#endif
#ifdef BUILD_BATOCERA
int wf=find_line(l,n,"WLAN"),bs=find_line(l,n,"Bluetooth System");if((b==BUTTON_A||b==BUTTON_DPAD_LEFT||b==BUTTON_DPAD_RIGHT)&&selected_line==wf){batocera_set_wifi_enabled(!batocera_wifi_enabled());return;}if((b==BUTTON_A||b==BUTTON_DPAD_LEFT||b==BUTTON_DPAD_RIGHT)&&selected_line==bs){batocera_set_bluetooth_enabled(!bluetooth_adapter_powered());return;}
#endif
if(b==BUTTON_A&&selected_line==oz){if(net_connection_active()){} }if(b==BUTTON_A&&selected_line==bd){*c->screen=SCREEN_BUTTON_DEBUG;return;}if(b==BUTTON_A&&selected_line==pl){logview_reset();*c->screen=SCREEN_LOG;return;}if(b==BUTTON_A&&selected_line==bt){if(bluetooth_adapter_powered()){bluetoothscreen_reset();*c->screen=SCREEN_BLUETOOTH;}return;}if(b==BUTTON_A&&selected_line==dl){if(!network_connection_active())return;downloadsettings_reset();*c->screen=SCREEN_DOWNLOAD_SETTINGS;return;}if(b==BUTTON_A&&selected_line==oz){if(!network_connection_active()||!stream_xml_url[0])return;streamsettings_reset();*c->screen=SCREEN_STREAM_SETTINGS;return;}if(b==BUTTON_A&&selected_line==up){updatesettings_reset();*c->screen=SCREEN_UPDATE_SETTINGS;return;}if((b==BUTTON_A||b==BUTTON_DPAD_LEFT||b==BUTTON_DPAD_RIGHT)&&selected_line==rl){toggle_repeat_book();return;}if(b==BUTTON_DPAD_LEFT&&selected_line==st){change_shutdown_tracks(-1);return;}if(b==BUTTON_DPAD_RIGHT&&selected_line==st){change_shutdown_tracks(1);return;}if((b==BUTTON_A||b==BUTTON_DPAD_LEFT||b==BUTTON_DPAD_RIGHT)&&selected_line==se){toggle_shutdown_end();return;}if(b==BUTTON_DPAD_LEFT&&selected_line==ov){change_output(-5);return;}if(b==BUTTON_DPAD_RIGHT&&selected_line==ov){change_output(5);return;}if(b==BUTTON_DPAD_LEFT&&selected_line==bv){change_bt(-5);return;}if(b==BUTTON_DPAD_RIGHT&&selected_line==bv){change_bt(5);return;}if(b==BUTTON_DPAD_LEFT&&selected_line==vl){change_volume(-VOLUME_STEP);return;}if(b==BUTTON_DPAD_RIGHT&&selected_line==vl){change_volume(VOLUME_STEP);return;}if(b==BUTTON_DPAD_LEFT&&selected_line==bl){change_brightness(-BRIGHTNESS_STEP);return;}if(b==BUTTON_DPAD_RIGHT&&selected_line==bl){change_brightness(BRIGHTNESS_STEP);return;}if(b==BUTTON_DPAD_LEFT&&selected_line==dt){change_display_timeout(-1);return;}if(b==BUTTON_DPAD_RIGHT&&selected_line==dt){change_display_timeout(1);return;}if(b==BUTTON_DPAD_LEFT&&selected_line==fl){menu_font_size=(menu_font_size+3)%4;save_state();keep_visible(n);return;}if(b==BUTTON_DPAD_RIGHT&&selected_line==fl){menu_font_size=(menu_font_size+1)%4;save_state();keep_visible(n);return;}if(b==BUTTON_DPAD_LEFT&&selected_line==ac){ui_accent_cycle(-1);return;}if(b==BUTTON_DPAD_RIGHT&&selected_line==ac){ui_accent_cycle(1);return;}
#ifdef BUILD_R36S
if(b==BUTTON_A&&selected_line==gl){led_reset_gpio_auto();return;}if((b==BUTTON_A||b==BUTTON_DPAD_LEFT||b==BUTTON_DPAD_RIGHT)&&selected_line==tl){led_set_test_mode(!led_test_mode());return;}if(b==BUTTON_DPAD_LEFT&&selected_line==gl){change_led_gpio(-1);return;}if(b==BUTTON_DPAD_RIGHT&&selected_line==gl){change_led_gpio(1);return;}
#endif
if(b==BUTTON_A&&selected_line==sl){confirm_sleep_timer(c);return;}if(b==BUTTON_A&&selected_line==il){*c->idle_timer_remaining_ms=idle_timer_minutes>0?(Uint32)idle_timer_minutes*60000U:0U;return;}if(b==BUTTON_DPAD_LEFT&&selected_line==sl){edit_sleep_timer(c,-SLEEP_STEP_MINUTES);return;}if(b==BUTTON_DPAD_RIGHT&&selected_line==sl){edit_sleep_timer(c,SLEEP_STEP_MINUTES);return;}if(b==BUTTON_DPAD_LEFT&&selected_line==il){change_idle_timer(-IDLE_TIMER_STEP_MINUTES);return;}if(b==BUTTON_DPAD_RIGHT&&selected_line==il){change_idle_timer(IDLE_TIMER_STEP_MINUTES);return;}}
if(e->type==SDL_JOYAXISMOTION){if(e->jaxis.axis==AXIS_Y){if(!*c->axis_y_lock&&e->jaxis.value<-AXIS_DEADZONE){selected_line=next_selectable(l,n,selected_line,-1);keep_visible(n);*c->axis_y_lock=1;}else if(!*c->axis_y_lock&&e->jaxis.value>AXIS_DEADZONE){selected_line=next_selectable(l,n,selected_line,1);keep_visible(n);*c->axis_y_lock=1;}if(abs(e->jaxis.value)<AXIS_DEADZONE)*c->axis_y_lock=0;}if(e->jaxis.axis==AXIS_X){if(!*c->axis_x_lock&&abs(e->jaxis.value)>AXIS_DEADZONE){int d=e->jaxis.value<0?-1:1;int vl=find_line(l,n,"Lautstaerke"),ov=find_line(l,n,"Ausgangslautstaerke"),bv=find_line(l,n,"Bluetooth-Lautstaerke"),bl=find_line(l,n,"Helligkeit"),dt=find_line(l,n,"Display aus nach"),fl=find_line(l,n,"Schriftgroesse"),ac=find_line(l,n,"Akzentfarbe"),sl=find_line(l,n,"Sleeptimer"),il=find_line(l,n,"Idle-Timer"),rl=find_line(l,n,"Hoerspielende"),st=find_line(l,n,"Shutdown nach Tracks"),se=find_line(l,n,"Shutdown am Ende");if(selected_line==ov)change_output(d*5);else if(selected_line==bv)change_bt(d*5);else if(selected_line==vl)change_volume(d*VOLUME_STEP);else if(selected_line==bl)change_brightness(d*BRIGHTNESS_STEP);else if(selected_line==dt)change_display_timeout(d);else if(selected_line==fl){menu_font_size=(menu_font_size+(d<0?3:1))%4;save_state();keep_visible(n);}else if(selected_line==ac)ui_accent_cycle(d);else if(selected_line==sl)edit_sleep_timer(c,d*SLEEP_STEP_MINUTES);else if(selected_line==il)change_idle_timer(d*IDLE_TIMER_STEP_MINUTES);else if(selected_line==rl)toggle_repeat_book();else if(selected_line==st)change_shutdown_tracks(d);else if(selected_line==se)toggle_shutdown_end();*c->axis_x_lock=1;}if(abs(e->jaxis.value)<AXIS_DEADZONE)*c->axis_x_lock=0;}}}
void systeminfo_render(ScreenContext*c){menu_font_apply(c->font);
#ifdef BUILD_R36S
led_test_tick(SDL_GetTicks());
#endif
InfoLine l[64];int n=build_lines(c,l),mo=n-MAX_VISIBLE;if(mo<0)mo=0;if(page_offset>mo)page_offset=mo;if(n>0&&!line_selectable(&l[selected_line]))selected_line=next_selectable(l,n,selected_line,1);keep_visible(n);draw_text(c->renderer,c->font,"Einstellungen",20,20,c->selected);int y=TOP_Y;for(int i=page_offset;i<n&&i<page_offset+MAX_VISIBLE;i++){if(l[i].heading)draw_text(c->renderer,c->font,l[i].label,25,y,c->selected);else{int dis=!line_selectable(&l[i]);SDL_Color col=dis?c->gray:(i==selected_line?c->selected:c->gray),vc=dis?c->gray:(i==selected_line?c->selected:c->white);draw_text(c->renderer,c->font,l[i].label,35,y,col);draw_text_right(c->renderer,c->font,l[i].value,SCREEN_W-35,y,vc);}y+=LINE_H;}if(n>MAX_VISIBLE){int th=SCREEN_H-95,hh=(th*MAX_VISIBLE)/n;if(hh<18)hh=18;int tr=th-hh,ty=55+(mo?(tr*page_offset)/mo:0);SDL_SetRenderDrawColor(c->renderer,70,70,80,255);SDL_Rect rail={SCREEN_W-8,55,2,th};SDL_RenderFillRect(c->renderer,&rail);SDL_SetRenderDrawColor(c->renderer,230,210,70,255);SDL_Rect thumb={SCREEN_W-8,ty,2,hh};SDL_RenderFillRect(c->renderer,&thumb);}draw_text(c->renderer,c->font,"B: Zurueck  A: OK/Auto  Hoch/Runter: Auswahl  Wert: Links/Rechts",20,SCREEN_H-25,c->gray);menu_font_restore(c->font);}